In [1]:
import tensorflow as tf

# Creating Dataset

In [7]:
dataset = tf.data.Dataset.range(10)
print(dataset)
print(type(dataset))

<RangeDataset shapes: (), types: tf.int64>
<class 'tensorflow.python.data.ops.dataset_ops.RangeDataset'>


In [8]:
for val in dataset:
  print(val)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [11]:
for val in dataset:
  print(val.numpy(), val.shape, val.ndim)

0 () 0
1 () 0
2 () 0
3 () 0
4 () 0
5 () 0
6 () 0
7 () 0
8 () 0
9 () 0


# Shifting Dataset

In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_ds in dataset:
  for val in window_ds:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [16]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_ds in dataset:
  for val in window_ds:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [18]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
print(dataset)

for window in dataset:
  print(window)

<FlatMapDataset shapes: (None,), types: tf.int64>
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int64)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [22]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

print(dataset)

for val in dataset:
  print(val)

for x,y in dataset:
  print(x.numpy(),y.numpy())

<MapDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([4])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([5])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 3, 4, 5])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([6])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 5, 6, 7])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([8])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 6, 7, 8])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([9])>)
[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [23]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)

print(dataset)

for val in dataset:
  print(val)

for x,y in dataset:
  print(x.numpy(),y.numpy())

<ShuffleDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 3, 4, 5])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([6])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([4])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 5, 6, 7])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([8])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([5])>)
(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 6, 7, 8])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([9])>)
[3 4 5 6] [7]
[2 3 4 5] [6]
[4 5 6 7] [8]
[0 1 2 3] [4]
[5 6 7 8] [9]
[1 2 3 4] [5]


In [26]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

print(dataset)
for val in dataset:
  print(val)

for x,y in dataset:
  print(x.numpy(),y.numpy())

<PrefetchDataset shapes: ((None, None), (None, None)), types: (tf.int64, tf.int64)>
(<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>, <tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[5],
       [9]])>)
(<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[3, 4, 5, 6],
       [4, 5, 6, 7]])>, <tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[7],
       [8]])>)
(<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[0, 1, 2, 3],
       [2, 3, 4, 5]])>, <tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[4],
       [6]])>)
[[3 4 5 6]
 [5 6 7 8]] [[7]
 [9]]
[[1 2 3 4]
 [0 1 2 3]] [[5]
 [4]]
[[2 3 4 5]
 [4 5 6 7]] [[6]
 [8]]


In [27]:
def window_dataset(series, window_size, batch_size=32, shuffle_buffer=1000):
  dataset = tf.data.Dataset.from_tensor_slices(series)
  dataset = dataset.window(size=window_size+1, shift=1, drop_remainder=True)
  dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
  dataset = dataset.shuffle(shuffle_buffer)
  dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
  dataset = dataset.batch(batch_size).prefetch(1)
  
  return dataset